<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            // ── Empresa: Cristian Padilla ─────────────────
            ['titulo' => 'Sistema de Gestión de Inventarios Inteligente', 'descripcion' => 'Desarrollo de una plataforma web para el control de stock en tiempo real utilizando Laravel y Vue.js. El sistema debe incluir alertas de bajo inventario y reportes predictivos con análisis de datos históricos para optimización de compras.', 'categoria' => 'tecnologia', 'estado' => 'en_progreso', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 90, 'requisitos_especificos' => 'Conocimientos en PHP, Laravel, Vue.js y bases de datos relacionales. Experiencia con APIs REST.', 'habilidades_requeridas' => 'Programación Web, SQL, Trabajo en equipo, Comunicación', 'imagen_url' => 'https://images.unsplash.com/photo-1586769852044-692d6e3703f0?q=80&w=800', 'oferta' => 'contrato_aprendizaje', 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'Rediseño de Identidad Visual Corporativa', 'descripcion' => 'Creación de un manual de identidad corporativa completo, incluyendo logo, paleta de colores, tipografía y aplicaciones en papelería institucional y digital.', 'categoria' => 'diseño', 'estado' => 'completado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 45, 'requisitos_especificos' => 'Manejo avanzado de Adobe Illustrator, Photoshop e InDesign.', 'habilidades_requeridas' => 'Diseño Gráfico, Branding, Creatividad, Pensamiento Visual', 'imagen_url' => 'https://images.unsplash.com/photo-1572044162444-ad60f128b7fa?q=80&w=800', 'oferta' => 'pasantias', 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'andrea.patino@sena.edu.co'],
            ['titulo' => 'Campaña de Marketing Digital SENA 2026', 'descripcion' => 'Diseño y ejecución de una estrategia integral de redes sociales para aumentar el engagement en Instagram, LinkedIn y TikTok, incluyendo content marketing y analytics.', 'categoria' => 'marketing', 'estado' => 'en_progreso', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 60, 'requisitos_especificos' => 'Certificación en Google Ads o Meta Blueprint. Experiencia con herramientas de scheduling.', 'habilidades_requeridas' => 'Copywriting, Analytics, Estrategia Digital, Creación de Contenido', 'imagen_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800', 'oferta' => 'auxilio_transporte', 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'App Móvil para Control de Asistencia', 'descripcion' => 'Creación de una aplicación móvil híbrida para registro de entrada y salida mediante geolocalización. Incluye módulo de reportes y notificaciones push.', 'categoria' => 'tecnologia', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 120, 'requisitos_especificos' => 'Experiencia previa con frameworks móviles como Ionic o Flutter.', 'habilidades_requeridas' => 'Mobile Development, APIs REST, Firebase, Geolocalización', 'imagen_url' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800', 'oferta' => 'contrato_aprendizaje', 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'Documental Institucional "Talento de Oro"', 'descripcion' => 'Producción audiovisual de 15 minutos capturando historias de éxito de los aprendices SENA. Incluye entrevistas, grabaciones en locación y postproducción.', 'categoria' => 'comunicacion', 'estado' => 'cerrado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 75, 'requisitos_especificos' => 'Conocimientos en edición de video (Premiere/DaVinci Resolve) y dirección audiovisual.', 'habilidades_requeridas' => 'Edición de Video, Fotografía, Narrativa Audiovisual, Dirección', 'imagen_url' => 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800', 'oferta' => 'pasantias', 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'andrea.patino@sena.edu.co'],
            ['titulo' => 'Plataforma E-commerce para Artesanos', 'descripcion' => 'Tienda en línea para artesanos locales con implementación de pasarelas de pago nacionales. Incluye panel de administración y gestión de inventario.', 'categoria' => 'tecnologia', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 100, 'requisitos_especificos' => 'Entendimiento de flujos de pago y seguridad web. Conocimiento en Laravel o similar.', 'habilidades_requeridas' => 'Web Development, UX/UI, Pasarelas de Pago, MySQL', 'imagen_url' => 'https://images.unsplash.com/photo-1557821552-17105176677c?q=80&w=800', 'oferta' => 'otro', 'oferta_otro' => 'Bonificación por desempeño', 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'Automatización de Procesos con Python', 'descripcion' => 'Scripts para automatizar la extracción de datos de reportes Excel y su carga en CRM corporativo. Incluye dashboard de métricas.', 'categoria' => 'tecnologia', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 30, 'requisitos_especificos' => 'Dominio de Python con librerías Pandas y Openpyxl.', 'habilidades_requeridas' => 'Python, Automatización, Ciencia de Datos, Excel Avanzado', 'imagen_url' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800', 'oferta' => 'auxilio_transporte', 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'Modelado 3D para Planta Industrial', 'descripcion' => 'Modelado tridimensional de una nueva ala de producción para simulaciones de seguridad y logística interna. Incluye renderizados y walkthrough virtual.', 'categoria' => 'ingenieria', 'estado' => 'pendiente', 'calidad_aprobada' => false, 'duracion_estimada_dias' => 80, 'requisitos_especificos' => 'Conocimiento en AutoCAD 3D o Blender avanzado.', 'habilidades_requeridas' => 'Modelado 3D, Planimetría, Renderizado, Visualización', 'imagen_url' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=800', 'oferta' => null, 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => null],
            ['titulo' => 'Sistema de Gestión de Pedidos Restaurant', 'descripcion' => 'App web para toma de pedidos en restaurantes con cocina digital y tracking de delivery.', 'categoria' => 'tecnologia', 'estado' => 'pendiente', 'calidad_aprobada' => false, 'duracion_estimada_dias' => 60, 'requisitos_especificos' => 'Conocimientos en Laravel y SQLite.', 'habilidades_requeridas' => 'Desarrollo Web, UI/UX', 'oferta' => null, 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => null],
            ['titulo' => 'Portal de Cursos Online', 'descripcion' => 'Plataforma de formación virtual con videos y evaluaciones.', 'categoria' => 'tecnologia', 'estado' => 'pendiente', 'calidad_aprobada' => false, 'duracion_estimada_dias' => 90, 'oferta' => null, 'oferta_otro' => null, 'empresa_email' => 'camilopineda182@gmail.com', 'instructor_email' => null],

            // ── Empresa: TechSolutions Colombia SAS ──────
            ['titulo' => 'Desarrollo de API Gateway para Pagos', 'descripcion' => 'Construcción de una API RESTful unificada que centralice múltiples pasarelas de pago (PSE, PayPal, Stripe) con manejo de transacciones, webhooks y dashboards de conciliación.', 'categoria' => 'tecnologia', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 75, 'requisitos_especificos' => 'Experiencia en desarrollo de APIs con Laravel y documentación OpenAPI.', 'habilidades_requeridas' => 'APIs REST, Laravel, Pasarelas de Pago, Seguridad Web', 'imagen_url' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=800', 'oferta' => 'contrato_aprendizaje', 'oferta_otro' => null, 'empresa_email' => 'contacto@techsolutions.co', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'Sistema de Análisis Predictivo con Machine Learning', 'descripcion' => 'Desarrollo de un motor de análisis predictivo para datos de ventas usando Python, scikit-learn y TensorFlow. Incluye pipeline de datos, entrenamiento de modelos y visualización de resultados.', 'categoria' => 'tecnologia', 'estado' => 'en_progreso', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 120, 'requisitos_especificos' => 'Conocimientos sólidos en Python, Pandas, scikit-learn y visualización de datos.', 'habilidades_requeridas' => 'Python, Machine Learning, Ciencia de Datos, SQL', 'imagen_url' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800', 'oferta' => 'contrato_aprendizaje', 'oferta_otro' => null, 'empresa_email' => 'contacto@techsolutions.co', 'instructor_email' => 'sherelynrocha939@gmail.com'],
            ['titulo' => 'Migración a Infraestructura Cloud', 'descripcion' => 'Planificación y ejecución de migración de infraestructura on-premise a AWS/Google Cloud. Incluye contenedorización con Docker, orquestación Kubernetes y automatización con Terraform.', 'categoria' => 'tecnologia', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 90, 'requisitos_especificos' => 'Certificación AWS Cloud Practitioner o equivalente. Conocimiento de Docker y Kubernetes.', 'habilidades_requeridas' => 'Cloud Computing, Docker, Kubernetes, Linux, DevOps', 'imagen_url' => 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?q=80&w=800', 'oferta' => 'pasantias', 'oferta_otro' => null, 'empresa_email' => 'contacto@techsolutions.co', 'instructor_email' => 'carlos.mendoza@sena.edu.co'],
            ['titulo' => 'Aplicación Web de Gestión Documental', 'descripcion' => 'Sistema de gestión documental con flujos de aprobación, OCR para digitalización, versionado de documentos y búsqueda semántica con Elasticsearch.', 'categoria' => 'tecnologia', 'estado' => 'pendiente', 'calidad_aprobada' => false, 'duracion_estimada_dias' => 100, 'requisitos_especificos' => 'Experiencia con Laravel, Elasticsearch y procesamiento de documentos.', 'habilidades_requeridas' => 'Laravel, Elasticsearch, UI/UX, Bases de Datos', 'imagen_url' => 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?q=80&w=800', 'oferta' => null, 'oferta_otro' => null, 'empresa_email' => 'contacto@techsolutions.co', 'instructor_email' => null],

            // ── Empresa: DiseñaStudio Creativo ──────────
            ['titulo' => 'Rebranding Corporativo para Fintech', 'descripcion' => 'Desarrollo de identidad visual completa para una startup fintech: logotipo, paleta cromática, tipografía, aplicaciones digitales, mockups de app y manual de marca.', 'categoria' => 'diseño', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 60, 'requisitos_especificos' => 'Portafolio demostrable en branding y diseño de identidad corporativa.', 'habilidades_requeridas' => 'Branding, Illustrator, Photoshop, Figma, Creatividad', 'imagen_url' => 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?q=80&w=800', 'oferta' => 'pasantias', 'oferta_otro' => null, 'empresa_email' => 'info@disenastudio.co', 'instructor_email' => 'andrea.patino@sena.edu.co'],
            ['titulo' => 'Diseño UI/UX para App de Fitness', 'descripcion' => 'Diseño de interfaz y experiencia de usuario para una aplicación móvil de entrenamiento personal. Incluye wireframes, prototipado interactivo en Figma y guía de componentes.', 'categoria' => 'diseño', 'estado' => 'en_progreso', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 45, 'requisitos_especificos' => 'Manejo avanzado de Figma, principios de UX research y diseño de interacción.', 'habilidades_requeridas' => 'UI/UX, Figma, Prototipado, Investigación de Usuarios', 'imagen_url' => 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?q=80&w=800', 'oferta' => 'auxilio_transporte', 'oferta_otro' => null, 'empresa_email' => 'info@disenastudio.co', 'instructor_email' => 'andrea.patino@sena.edu.co'],
            ['titulo' => 'Animación 2D para Video Promocional', 'descripcion' => 'Creación de video animado 2D de 60 segundos para campaña de lanzamiento de producto. Incluye storyboard, ilustración de personajes, animación y postproducción de audio.', 'categoria' => 'comunicacion', 'estado' => 'pendiente', 'calidad_aprobada' => false, 'duracion_estimada_dias' => 40, 'requisitos_especificos' => 'Conocimiento en After Effects, animación de personajes y diseño sonoro.', 'habilidades_requeridas' => 'After Effects, Animación 2D, Ilustración, Edición de Audio', 'imagen_url' => 'https://images.unsplash.com/photo-1536240478700-b869070f9279?q=80&w=800', 'oferta' => null, 'oferta_otro' => null, 'empresa_email' => 'info@disenastudio.co', 'instructor_email' => null],

            // ── Empresa: IngeProyectos LTDA ──────────────
            ['titulo' => 'Diseño de Instalaciones Eléctricas Residenciales', 'descripcion' => 'Elaboración de planos y memorias de cálculo para instalaciones eléctricas de un conjunto residencial de 20 unidades. Incluye diseño de iluminación, fuerza y sistemas de puesta a tierra.', 'categoria' => 'ingenieria', 'estado' => 'aprobado', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 50, 'requisitos_especificos' => 'Conocimiento en RETIE, NTC 2050 y manejo de AutoCAD eléctrico.', 'habilidades_requeridas' => 'AutoCAD, Instalaciones Eléctricas, RETIE, Cálculos Eléctricos', 'imagen_url' => 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800', 'oferta' => 'auxilio_transporte', 'oferta_otro' => null, 'empresa_email' => 'proyectos@ingepro.co', 'instructor_email' => 'roberto.vega@sena.edu.co'],
            ['titulo' => 'Automatización PLC para Línea de Producción', 'descripcion' => 'Programación e implementación de controlador lógico programable (PLC) para automatizar línea de ensamble. Incluye diseño de HMI, sensores y actuadores, y pruebas de integración.', 'categoria' => 'ingenieria', 'estado' => 'en_progreso', 'calidad_aprobada' => true, 'duracion_estimada_dias' => 90, 'requisitos_especificos' => 'Experiencia en programación de PLC (Siemens o Allen-Bradley) y diseño de tableros de control.', 'habilidades_requeridas' => 'PLC, Automatización, HMI, Electricidad Industrial, Instrumentación', 'imagen_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800', 'oferta' => 'contrato_aprendizaje', 'oferta_otro' => null, 'empresa_email' => 'proyectos@ingepro.co', 'instructor_email' => 'roberto.vega@sena.edu.co'],
            ['titulo' => 'Estudio de Iluminación para Edificio Corporativo', 'descripcion' => 'Estudio técnico y diseño de sistema de iluminación LED para edificio de 10 pisos. Incluye cálculos luminotécnicos, selección de luminarias, planos y simulación en DIALux.', 'categoria' => 'ingenieria', 'estado' => 'pendiente', 'calidad_aprobada' => false, 'duracion_estimada_dias' => 35, 'requisitos_especificos' => 'Manejo de DIALux o software similar de simulación lumínica.', 'habilidades_requeridas' => 'DIALux, Iluminación, AutoCAD, Eficiencia Energética', 'imagen_url' => 'https://images.unsplash.com/photo-1581092795607-f96c2242a3b5?q=80&w=800', 'oferta' => null, 'oferta_otro' => null, 'empresa_email' => 'proyectos@ingepro.co', 'instructor_email' => null],
        ];

        foreach ($projects as $data) {
            $companyNit = DB::table('empresas')->where('correo_contacto', $data['empresa_email'])->value('nit');
            $instructorId = $data['instructor_email']
                ? DB::table('usuarios')->where('correo', $data['instructor_email'])->value('id')
                : null;
            $estado = $data['estado'];
            $asignarInstructor = in_array($estado, ['aprobado', 'en_progreso', 'completado', 'cerrado']);

            unset($data['empresa_email'], $data['instructor_email']);

            DB::table('proyectos')->insertOrIgnore(array_merge($data, [
                'empresa_nit'           => $companyNit,
                'instructor_usuario_id' => $asignarInstructor ? $instructorId : null,
                'fecha_publicacion'     => Carbon::now()->toDateString(),
                'numero_postulantes'    => 0,
                'created_at'            => now(),
                'updated_at'            => now(),
            ]));
        }

        $this->command->info(count($projects).' Proyectos de ejemplo insertados correctamente.');
    }
}
